name: CI Build


on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  Milestone-Check:
    name: Checks if milestone is used
    runs-on: ubuntu-latest
    steps:
      - name: Has milestone check
        if: github.event.pull_request.milestone == null
        run: |
          echo "you don't have a milestone"
          exit 1

  Label-Check:
    name: Checks if labels are used
    runs-on: ubuntu-latest

    steps:
      - name: Checking out to the develop branch
        uses: actions/checkout@v2

      - name: Has atleast one priority label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "priority:high, priority:low, priority:medium"

      - name: Has atleast one type label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "type:bug, type:change, type:documentation, type:enhance, type:fix, type:meeting, type:test"

      - name: Has atleast one status label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "status:needs-tests, status:not-ready, status:ready"

      - name: Has atleast one role label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "role:frontend-engineer, role:business-analyst, role:backend-engineer, role:dev-op, role:team-lead, role:tester, role:designer"

      - name: Has atleast one scope label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "scope:ai, scope:cicd, scope:github-repo, scope:db, scope:frontend,scope:backend"

  Twitter-Summariser-Frontend:
    name: Testing and building of frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Twitter-Summariser/client

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: 'yarn'

      - name: Install all frontend package dependencies
        run:  yarn

      - name: Run the linter for frontend
        run:  yarn lint

      - name: Run frontend tests
        run:  yarn test --coverage --watchAll=false

      - name: Build the React App
        run:  yarn run build

      - name: Upload client coverage folder as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-artifact
          path: Twitter-Summariser/client/coverage/

  Twitter-Summariser-Backend:
    name: Testing of backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Twitter-Summariser

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: 'yarn'

      - name: Install all backend package dependencies
        run: yarn

      - name: Run the unit tests
        run: yarn test -- --coverage
      
      # - name: Run the integration tests
      #   run: yarn test:int

      - name: Upload backend coverage folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: Twitter-Summariser/coverage/