name: "Twitter Summariser CI"

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  lint-and-format:
    name: Attempt to lints and format all code in the repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install all backend package dependencies
        run:  |
          yarn
          cd client
          yarn

      - name: Run the linter and attempt to fix errors
        run: yarn lint:fix

  Frontend:
    name: Testing and building of frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: 'yarn'

      - name: Install all frontend package dependencies
        run:  |
          cd client
          yarn
          yarn test --coverage --watchAll=false


      # - name: Run frontend tests
      #   run:  yarn test --coverage --watchAll=false
      #   env:
      #     CI: false

      - name: Build the React App
        run:  yarn run build

      - name: Upload client coverage folder & build forder as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-artifact
          path: client/coverage/

  Backend:
    name: Testing of backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: 'yarn'

      - name: Install all backend package dependencies
        run: yarn

      - name: Run the tests
        run: yarn test -- --coverage

      - name: Upload backend coverage folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: coverage/
