name: "Twitter Summariser CI"

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  lint-and-format:
    name: Attempt to lints and format all code in the repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install all backend package dependencies
        run:  |
          yarn
          cd client
          yarn

      - name: Run the linter and attempt to fix errors
        run: yarn lint:fix

      - name: Run Prettier and fomat the code
        run:  yarn format

  frontend:
    name: Testing and building of frontend
    needs: lint-and-format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install all frontend package dependencies
        run:  yarn

      - name: Run frontend tests
        run:  yarn test --coverage --watchAll=false

      - name: Build the React App
        run:  yarn run build

      - name: Upload client coverage folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-artifact
          path: client/coverage/

  backend:
    name: Testing of backend
    needs: lint-and-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install all backend package dependencies
        run: yarn

      - name: Run the tests
        run: yarn test -- --coverage

      - name: Upload backend coverage folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: coverage/