name: Serverless Deploy

on:
  pull_request:
    branches: [develop, master]
    types:
      - closed

jobs:
  Deploy:
    name: Deployment of the Twitter Summariser and Text-Summarisation Module
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop/master branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install serverless compose dependencies
        run: yarn

      - name: Build the Twitter Summariser App
        run: |
          cd app/client
          yarn
          CI=false yarn run build

      - name: Install package dependencies for backend
        run: |
          cd app
          yarn

      - name: Deployment of All Infrastructures to AWS
        uses: dhollerbach/actions.serverless-with-python-requirements@master
        with:
          args: ""
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidating Cloudfrount S3 Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          npm i @aws-cdk/aws-cloudfront
          aws cloudfront create-invalidation --distribution-id E1R142F8OZ0I9V --paths "/*"
