name: React CI/CD

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

defaults:
  run:
    working-directory: client

jobs:
  Build-and-Deploy-React-App:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install all package dependencies
        run: npm install

      - name: Lint the code and format the files
        run: npm run test-eslint

      - name: Build the project
        run: npm run build

      - name: Configure AWS tokens
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy the React App to S3 Bucket
        run: aws s3 cp build s3://twitter-summariser-bucket/ --recursive

