name: "Twitter Summariser CI"

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  milestone-check:
    name: Checks if milestone is used
    runs-on: ubuntu-latest
    steps:
      - name: Has milestone check
        if: github.event.pull_request.milestone == null
        run: |
          echo Yyou don't have a milestone"
          exit 1

  label-check:
    name: Checks if labels are used
    runs-on: ubuntu-latest
    steps:
      - name: Has atleast one priority label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "priority:high, priority:low, priority:medium"

      - name: Has atleast one type label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "type:bug, type:change, type:documentation, type:enhance, type:fix, type:meeting, type:test"

      - name: Has atleast one status label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "status:needs-tests, status:not-ready, status:ready"

      - name: Has atleast one role label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "role:frontend-engineer, role:business-analyst, role:backend-engineer, role:dev-op, role:team-lead, role:tester, role:designer"

      - name: Has atleast one scope label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "scope:ai, scope:cicd, scope:github-repo, scope:db, scope:frontend,scope:backend"

  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'src/**'
              - '*.json'
              - '*.js'
              - '*.ts'
              - '*.nvmrc'
              - 'yarn.lock'
            frontend:
              - 'client/**'

  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install all package dependencies
        run: yarn

      - name: Build the React App
        run: CI=false yarn run build

      - name: Run frontend tests
        run: yarn test --watchAll=false

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install all package dependencies
        run: yarn

      - name: Run the tests
        run: yarn test
